### PR TITLE
Upgrade project to zig 0.10, and fix including the library in another project

### PR DESCRIPTION
**Pull request by viviicat**
The main change is an update for the new Pkg struct layout.

It seems that I had to make some changes to how the paths are resolved so that they are resolved from the Zig-VMA root rather than from my root. But this may be related to how I am pulling in the dependencies as a submodule/with [gyro](https://github.com/mattnite/gyro).

### CODE REVIEW

**Comment by viviicat** [comment]
Now seeing some compiler errors with zig 0.10, so I'll keep iterating on this.

**Comment by SpexGuy** [comment]
Thanks for the push on this! I took these changes plus some others and set it up to work with 0.10.0+dev as well as 0.9.0 and 0.9.1.  I also took the opportunity to restructure the project for easier use as a package.  See the new readme for instructions on using the new vma_build.zig file.  I've also updated [SpexGuy/sdltest](https://github.com/SpexGuy/sdltest) to use this style of import as an example.  Please let me know if anything is still causing trouble for you.

**Comment by viviicat** [comment]
> Please let me know if anything is still causing trouble for you.

Thanks, this seems a lot cleaner. Unfortunately I am still getting an error. I imagine it's probably because I'm not using your Zig-Vulkan-Headers library for my vulkan, but rather https://github.com/Snektron/vulkan-zig.

I'm assuming there isn't a lot you can do about that, though.

```
./.gyro/Zig-VMA-SpexGuy-github.com-1f74653e/pkg/vma.zig:947:14: error: container '.vulkan' has no member called 'CallConv'
) callconv(vk.CallConv) void;
             ^
./.gyro/Zig-VMA-SpexGuy-github.com-1f74653e/pkg/vma.zig:1160:5: note: while checking this field
    pDeviceMemoryCallbacks: ?*const DeviceMemoryCallbacks = null,
    ^
./.gyro/Zig-VMA-SpexGuy-github.com-1f74653e/pkg/vma.zig:1027:37: error: expected 2 argument(s), found 1
    pub usingnamespace vk.FlagsMixin(@This());
                                    ^
./zig-cache/vk.zig:18:5: note: declared here
pub fn FlagsMixin(comptime FlagsType: type, comptime Int: type) type {
    ^
```

**Comment by SpexGuy** [comment]
Ah, yeah, you may need to make a fork for those changes.  The relevant changes are:
- `vk.CallConv` becomes `vk.vulkan_call_conv`.
- calls to `FlagsMixin` take `u32` as an additional argument.
- the `VulkanFunctions` field types need to be changed to use the relevant `vk.Pfn*` declarations.

**Comment by viviicat** [comment]
Yes, I am experimenting with those changes. Strangely enough, once I make those changes I get the error that `parameter of type '.vma.AllocatorCreateInfo' must be declared comptime`, and if I add that, the compiler crashes with `Assertion failed at /home/vv/Projects/zig/src/stage1/analyze.cpp:430 in get_abi_alignment. This is a bug in the Zig compiler.thread 4150`. Very strange.

**Comment by SpexGuy** [comment]
Hmm, that's very strange.  The parameter definitely should not need to be comptime, and apparently can't be.  It's possible that the compiler thinks `AllocatorCreateInfo` is a comptime-only type for some reason.  Maybe try removing fields from it and see if that works? (it would crash due to a mismatch between C and Zig's declarations, but it might at least provide some insight.)

**Comment by viviicat** [comment]
FWIW, I figured it out. Zig compiler was not producing a helpful error. But the issue was I was using `@typeOf(PfnFoo)` instead of just `PfnFoo` -- as the PfnFoos are already a type rather than a function itself. So, it was creating a struct containing types, which can only be comptime. Once I removed the `@typeOf`s and passed the raw Pfns in, the errors went away (*phew*)
